## Assignment-07 First Step of using machine learning and models.

![](https://github.com/Computing-Intelligence/jupyters_and_slides/raw/master/entrance-test/images/kkb-ai.png)

In [104]:
fname = '/Users/zhangjie/Documents/machinelearning/att/nplAssignments-local/sqlResult_1558435.csv'

In [105]:
import pandas as pd

In [106]:
content = pd.read_csv(fname, encoding='gb18030')
print(len(content))

89611


In [107]:
content.head()

id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

In [108]:
xinhua_news = content[content['source'] == '新华社']

In [109]:
len(xinhua_news) / len(content)

0.8778051801676133

### 任务描述

报社等相关的机构，往往会遇到一个问题，就是别人家的机构使用自己的文章但是并没有标明来源。 在本次任务中，我们将解决新华社的文章被抄袭引用的问题。

给定的数据集合中，存在一些新闻预料，该预料是来自新华社，但是其来源并不是新华社，请设计技巧学习模型解决该问题。

![](https://timgsa.baidu.com/timg?image&quality=80&size=b9999_10000&sec=1566105348906&di=ee9a2de91207767364853d4decc6cca3&imgtype=0&src=http%3A%2F%2Fmmbiz.qpic.cn%2Fmmbiz_png%2FTicO2kbP6Ao5sCsSQDpehZiczLdC6hDCNvoicjcOCEKX2bLxBc9gVOw28zHyFibfIWq9ceRibP6HDTKReGkr6YyTfQQ%2F640%3Fwx_fmt%3Dpng)

### Step1: 数据分析

请在课程的GitHub中下载数据集，然后使用pandas进行读取。

In [110]:
import pandas as pd
fname = '/Users/zhangjie/Documents/machinelearning/att/nplAssignments-local/sqlResult_1558435.csv'
data = pd.read_csv(fname, encoding='gb18030')
xinhua_news = data[content['source']=='新华社']
print(len(xinhua_news))
len(xinhua_news) / len(data)
data.head()

78661


id      author                  source  \
0  89617         NaN  快科技@http://www.kkj.cn/   
1  89616         NaN  快科技@http://www.kkj.cn/   
2  89615         NaN  快科技@http://www.kkj.cn/   
3  89614         NaN                     新华社   
4  89613  胡淑丽_MN7479                   深圳大件事   

                                             content  \
0  此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1  骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2  此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3    这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4  （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   

                                             feature  \
0  {"type":"科技","site":"cnbeta","commentNum":"37"...   
1  {"type":"科技","site":"cnbeta","commentNum":"15"...   
2  {"type":"科技","site":"cnbeta","commentNum":"18"...   
3  {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4  {"type":"新闻","site":"网易热门","commentNum":"978",...   

                           title  \
0           小米MIUI 9首批机型曝光：共计15款   
1     骁龙835在Windows 10上的性能表现有望改善   
2      一加手机5细节曝光：3300mAh、充半小时用1天   
3  葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4       44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   

                                                 url  
0     http://www.cnbeta.com/articles/tech/623597.htm  
1     http://www.cnbeta.com/articles/tech/623599.htm  
2     http://www.cnbeta.com/articles/tech/623601.htm  
3  http://world.huanqiu.com/hot/2017-06/10866126....  
4  http://news.163.com/17/0618/00/CN617P3Q0001875...

### Step2: 数据预处理

将pandas中的数据，依据是否是新华社的文章，请改变成新的数据dataframe: <content, y>, 其中，content是文章内容，y是0或者1. 你可能要使用到pandas的dataframe操作。https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.apply.html

In [111]:
type(data)

pandas.core.frame.DataFrame

In [112]:
def get_size(data,colume):
    size_colume=0
    for i in range(len(data[colume])):
        if isinstance(data[colume][i],str):
            size_colume +=len(data[colume][i])
    ave_size_colume = size_colume/len(data[colume])
    print('colume: ',colume,' ',ave_size_colume)
for s in ['author','source','content','feature','title','url']:
    get_size(data,s)
        
    
    

colume:  author   5.6409815759225985
colume:  source   3.2928546718594816
colume:  content   432.1927665130397
colume:  feature   596.4780439901351
colume:  title   23.69386570845097
colume:  url   83.39267500641662


In [113]:
import numpy as np
data['is_xinhua']=np.where(data['source'].fillna('').str.contains('新华'),1,0)
                                                   

In [114]:
X = [[0], [1], [2], [3]]
y = [0, 0, 1, 1]
from sklearn.neighbors import KNeighborsClassifier
neigh = KNeighborsClassifier(n_neighbors=3)
neigh.fit(X, y) 

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=3, p=2,
                     weights='uniform')

In [115]:
print(neigh.predict([[1.1]]))
print(neigh.predict_proba([[0.9]]))

[0]
[[0.66666667 0.33333333]]


In [116]:
samples = [[0., 0., 0.], [0., .5, 0.], [1., 1., .5]]
from sklearn.neighbors import NearestNeighbors
neigh = NearestNeighbors(n_neighbors=1)
neigh.fit(samples) 

NearestNeighbors(algorithm='auto', leaf_size=30, metric='minkowski',
                 metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                 radius=1.0)

In [117]:
print(neigh.kneighbors([[1., 1., 1.]])) 

(array([[0.5]]), array([[2]]))


In [118]:
X = [[0., 1., 0.], [1., 0., 1.]]
print(neigh.kneighbors(X, return_distance=False))
print(neigh.kneighbors(X))

[[1]
 [2]]
(array([[0.5       ],
       [1.11803399]]), array([[1],
       [2]]))


### Step3: 使用tfidf进行文本向量化

参考 https://scikit-learn.org/stable/modules/generated/sklearn.feature_extraction.text.TfidfVectorizer.html 对

对文本进行向量化

In [119]:
data

id      author                  source  \
0      89617         NaN  快科技@http://www.kkj.cn/   
1      89616         NaN  快科技@http://www.kkj.cn/   
2      89615         NaN  快科技@http://www.kkj.cn/   
3      89614         NaN                     新华社   
4      89613  胡淑丽_MN7479                   深圳大件事   
...      ...         ...                     ...   
89606      5          邹峥                     新华社   
89607      4          王衡                     新华社   
89608      3          张旌                     新华社   
89609      2         夏文辉                     新华社   
89610      1      王子江 张寒                     新华社   

                                                 content  \
0      此外，自本周（6月12日）起，除小米手机6等15款机型外，其余机型已暂停更新发布（含开发版/...   
1      骁龙835作为唯一通过Windows 10桌面平台认证的ARM处理器，高通强调，不会因为只考...   
2      此前的一加3T搭载的是3400mAh电池，DashCharge快充规格为5V/4A。\r\n...   
3        这是6月18日在葡萄牙中部大佩德罗冈地区拍摄的被森林大火烧毁的汽车。新华社记者张立云摄\r\n   
4      （原标题：44岁女子跑深圳约会网友被拒，暴雨中裸身奔走……）\r\n@深圳交警微博称：昨日清...   
...                                                  ...   
89606  新华社照片，多伦多，2017年6月7日\n（体育）（2）冰球——国家女子冰球队海外选秀在多伦...   
89607  新华社兰州6月3日电（王衡、徐丹）记者从甘肃省交通运输厅获悉，甘肃近日集中开建高速公路、普通...   
89608  \n\n2017年5月29日，在法国巴黎郊外的凡尔赛宫，法国总统马克龙出席新闻发布会。（新华...   
89609  \n\n2017年5月25日，在美国马萨诸塞州剑桥市，哈佛大学毕业生在毕业典礼上欢呼。（新华...   
89610  　　新华社德国杜塞尔多夫６月６日电题：乒乓女球迷　\n　　新华社记者王子江、张寒\n　　熊老...   

                                                 feature  \
0      {"type":"科技","site":"cnbeta","commentNum":"37"...   
1      {"type":"科技","site":"cnbeta","commentNum":"15"...   
2      {"type":"科技","site":"cnbeta","commentNum":"18"...   
3      {"type":"国际新闻","site":"环球","commentNum":"0","j...   
4      {"type":"新闻","site":"网易热门","commentNum":"978",...   
...                                                  ...   
89606  {"type":"冰球","site":"新华社","url":"http://home.x...   
89607  {"type":"宏观经济","site":"新华社","url":"http://home...   
89608  {"type":"其它","site":"新华社","url":"http://home.x...   
89609  {"type":"其它","site":"新华社","url":"http://home.x...   
89610  {"type":"体育","site":"新华社","url":"http://home.x...   

                               title  \
0               小米MIUI 9首批机型曝光：共计15款   
1         骁龙835在Windows 10上的性能表现有望改善   
2          一加手机5细节曝光：3300mAh、充半小时用1天   
3      葡森林火灾造成至少62人死亡 政府宣布进入紧急状态（组图）   
4           44岁女子约网友被拒暴雨中裸奔 交警为其披衣相随   
...                              ...   
89606   （体育）（2）冰球——国家女子冰球队海外选秀在多伦多展开   
89607          （经济）甘肃集中开工35个重点交通建设项目   
89608           法国议会选举　马克龙有望获“压倒性胜利”   
89609              哈佛大学为何取消这些新生入选资格？   
89610                   （体育）题：乒乓女球迷　   

                                                     url  is_xinhua  
0         http://www.cnbeta.com/articles/tech/623597.htm          0  
1         http://www.cnbeta.com/articles/tech/623599.htm          0  
2         http://www.cnbeta.com/articles/tech/623601.htm          0  
3      http://world.huanqiu.com/hot/2017-06/10866126....          1  
4      http://news.163.com/17/0618/00/CN617P3Q0001875...          0  
...                                                  ...        ...  
89606  http://home.xinhua-news.com/gdsdetailxhsnew/22...          1  
89607  http://home.xinhua-news.com/gdsdetailxhsnew/22...          1  
89608  http://home.xinhua-news.com/gdsdetailxhsnew/22...          1  
89609  http://home.xinhua-news.com/gdsdetailxhsnew/22...          1  
89610  http://home.xinhua-news.com/gdsdetailxhsnew/22...          1  

[89611 rows x 8 columns]

In [120]:
data = data[data['content'].notnull()]
data_xinhua_pos = data[data['source'].fillna('').str.contains('新华')]
data_xinhua_neg = data[data['source'].fillna('').str.contains('新华')==0]
print(len(data_xinhua_pos))
print(len(data_xinhua_neg))
print(len(data_xinhua_pos)/len(data))

78855
8199
0.90581707905438


In [146]:
N=4000
data_xinhua_neg_sample = data_xinhua_neg.sample(N)
data_xinhua_pos_sample = data_xinhua_pos.sample(N)
print(len(data_xinhua_pos_sample))

4000


In [147]:
data_samples = data_xinhua_neg_sample.append(data_xinhua_pos_sample)
print(len(data_samples))
data_samples['content'][:10]

8000


4519    央视网消息：据中央纪委监察部网站消息，“今年前5月共结案39件，同比上升50%；处分39人，...
2692    　　创新层企业奥特美克(430245)6月15日公告，2017年6月14日，宁夏自治区中卫市...
4894    中新网6月21日电? 移动大数据分析公司Trustdata发布了《2017年Q1中国移动互联...
7869    　　运用站点尺度橡胶林生态系统碳汇评估体系，通过长期定位观测并结合遥感技术研究，热科院橡胶所...
6476    　　调研组一行早上首先来到保亭什玲镇水尾村和响水镇什月村，详细了解贫困户危房改造、整村推进项...
1943    　　2017年全球经济增速放缓成为不争事实，作为经济先行指标的铜也深受影响，从全球显性库存观...
6160    近几个月来，不少媒体陆续到山根村我闻和松塘村我闻这两家民宿采访。不过，眼下的爆红并没有打乱民...
6709    境外购“养生物件” 当心辐射超标伤身\r\n　　据新华社福州电?（记者李慧颖）记者从福建检验...
1916    （原标题：特朗普古巴新政获古巴强硬派青睐：让我们更团结）\r\n特朗普古巴新政获古巴强硬派青...
1489    　　特约撰稿 朱丽娜 香港报道\r\n　　导读\r\n　　港交所人士表示，符合要求的境外投资...
Name: content, dtype: object

In [148]:
import jieba
import re
#attributes=['author','source','content','feature','title']
attributes=['content']
def cut(str):
    return ' '.join(jieba.cut(re.sub(r'[^\w\s]',' ',str.strip())))
def propropess(sourcedata):
    for att in attributes:
        sourcedata[att]=sourcedata[att].fillna('').apply(cut)
    return sourcedata[att],sourcedata['is_xinhua']

x_samples,y_samples = propropess(data_samples)

                                    
    

In [149]:
x_samples[:10]

4519    央视网 消息   据 中央纪委 监察部 网站 消息     今年 前 5 月 共 结案 39...
2692    创新 层 企业 奥特 美克   430245   6 月 15 日 公告   2017 年 ...
4894    中新网 6 月 21 日电     移动 大 数据分析 公司 Trustdata 发布 了 ...
7869    运用 站点 尺度 橡胶林 生态系统 碳汇 评估 体系   通过 长期 定位 观测 并 结合 ...
6476    调研组 一行 早上 首先 来到 保亭 什玲镇 水尾村 和 响水 镇什月村   详细 了解 贫...
1943    2017 年 全球 经济 增速 放缓 成为 不争 事实   作为 经济 先行 指标 的 铜 ...
6160    近几个月 来   不少 媒体 陆续 到 山根 村 我闻 和 松 塘村 我闻 这 两家 民宿 ...
6709    境外 购   养生 物件     当心 辐射 超标 伤身 \r\n 　 　 据 新华社 福州...
1916      原 标题   特朗普 古巴 新政 获 古巴 强硬派 青睐   让 我们 更 团结   \...
1489    特约 撰稿   朱丽娜   香港 报道 \r\n 　 　 导读 \r\n 　 　 港交所 人...
Name: content, dtype: object

In [150]:
y_samples

4519     0
2692     0
4894     0
7869     0
6476     0
        ..
60709    1
49020    1
21941    1
77364    1
58498    1
Name: is_xinhua, Length: 8000, dtype: int64

In [151]:
from sklearn.feature_extraction.text import TfidfVectorizer
vectorizer = TfidfVectorizer()
x_tfidf_samples = vectorizer.fit_transform(x_samples).toarray()


### Step4: 参考scikit-learning的方法，构建你的第一个机器学习模型

In [152]:
print(x_tfidf_samples)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


+ 按照课程讲解的内容，把数据集分割为 traning_data, validation_data, test_data. https://scikit-learn.org/stable/modules/generated/sklearn.model_selection.train_test_split.html

In [153]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x_tfidf_samples,y_samples,train_size = 0.8, test_size=0.2)
print(x_train)
print(y_train)
print(x_test)
print(y_test)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
4759     0
27101    1
28329    1
6847     0
18869    1
        ..
51782    1
1100     0
39540    1
5608     0
4147     0
Name: is_xinhua, Length: 6400, dtype: int64
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
708      0
83733    1
6097     0
3252     0
5512     0
        ..
988      0
6465     0
1811     0
42549    1
297      0
Name: is_xinhua, Length: 1600, dtype: int64


+ 参照scikit learning的示例，从构建你的第一个KNN机器学习模型。

In [154]:
#使用KNN方法
from sklearn.neighbors import KNeighborsClassifier
neighs = KNeighborsClassifier(n_neighbors=5, weights = 'uniform', algorithm = 'auto')
neighs.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

### Step5: 在traning_data, validation_data, test_data 上观察其相关metric: recall, precision, f1等， 并解释其含义. 

In [155]:
from sklearn.metrics import f1_score
from sklearn.metrics import accuracy_score
from sklearn.metrics import precision_score
from sklearn.metrics import recall_score
def get_performance(clf,x_,y_):
    y_hat = clf.predict(x_)
    f1score = f1_score(y_,y_hat)
    accuracyscore=accuracy_score(y_,y_hat)
    precisionscore=precision_score(y_, y_hat)
    recallscore=recall_score(y_, y_hat)
    print("f1_score is ",f1score)
    print("accuracy_score is ",accuracyscore)
    print("precision_score is ",precisionscore)
    print("recall_score is ",recallscore)

In [168]:
get_performance(neighs,x_test,y_test)

f1_score is  0.6957279860505667
accuracy_score is  0.56375
precision_score is  0.5348525469168901
recall_score is  0.9950124688279302


### Step6: 使用 test_data 对其进行新数据的判断, 你有没

In [145]:
#GridSearchCV自动调参
from sklearn.model_selection import GridSearchCV
clff = KNeighborsClassifier()
param_grid = { 'n_neighbors' : [i for i in range(1,6)]}
print(param_grid)
grid = GridSearchCV(clff, param_grid, cv = 2, scoring='accuracy',n_jobs = -1)
clff = grid.fit(x_train, y_train)
print(clff.best_params_)

{'n_neighbors': [1, 2, 3, 4, 5]}
{'n_neighbors': 4}


/anaconda3/envs/NPL-3.6/lib/python3.6/site-packages/sklearn/model_selection/_search.py:814: DeprecationWarning: The default of the `iid` parameter will change from True to False in version 0.22 and will be removed in 0.24. This will change numeric results when test-set sizes are unequal.
  DeprecationWarning)


### Step7: 调整不同的参数，观察变化

In [ ]:
#get_performance(clff,x_test,y_test)

In [169]:
y_predict=neighs.predict(x_test)
print(type(y_predict))
y_predict

<class 'numpy.ndarray'>


array([1, 1, 0, ..., 1, 1, 1])

### Step8: 不断改变参数，直到性能达到“某个”点。问：“某个”怎么定义？

In [33]:
# it's your time

### Step9: 找出所以预测为 1， 但是实际为 0 的文章。 作为抄袭的候选者。

In [163]:
print(y_test)
print(len(y_test))
print(np.array(y_test)[0])
print(type(y_test))

# y_test[y_test==0]
# np.array(y_test)
print(y_test.index)
print(y_predict)
print(np.array(y_test))

708      0
83733    1
6097     0
3252     0
5512     0
        ..
988      0
6465     0
1811     0
42549    1
297      0
Name: is_xinhua, Length: 1600, dtype: int64
1600
0
<class 'pandas.core.series.Series'>
Int64Index([  708, 83733,  6097,  3252,  5512,  3346,  3337,  1028,  1986,
             1308,
            ...
            76639,  2364,  6773,  2527,  1020,   988,  6465,  1811, 42549,
              297],
           dtype='int64', length=1600)
[1 1 0 ... 1 1 1]
[0 1 0 ... 0 1 0]


In [165]:
print(len(y_test))
print(len(y_predict))
def getresult(y_predict):
    indexs=[]
    for i in range(len(y_test)):
        if(np.array(y_test)[i]==0 and y_predict[i]==1):
            indexs.append(y_test.index[i])
    print(len(indexs))
    print(indexs)

    for i in range(len(indexs)):
        print(data.iloc[indexs[i], :])
getresult(y_predict)    



1600
1600
694
[708, 5512, 3337, 1028, 1986, 1308, 4756, 3160, 10581, 1920, 6131, 5519, 3091, 466, 10742, 3359, 7279, 4267, 6424, 6403, 10962, 43, 5618, 7788, 3301, 7909, 6905, 2351, 919, 6237, 6160, 2074, 1807, 6584, 2994, 879, 6394, 6520, 6476, 6136, 4281, 4643, 344, 3214, 4819, 5540, 7622, 6011, 4236, 544, 6302, 6089, 6794, 5973, 10817, 3311, 1995, 4579, 188, 2493, 4526, 1467, 892, 429, 2248, 6876, 3869, 5254, 7128, 3193, 5400, 6032, 4294, 1499, 1894, 683, 174, 4585, 5808, 3956, 6310, 9131, 7524, 7921, 7047, 5539, 6607, 1373, 6073, 3846, 971, 10811, 6427, 1554, 5976, 5238, 8072, 5305, 7421, 5202, 187, 6402, 393, 10042, 7419, 1326, 2058, 1429, 784, 4650, 2266, 7367, 2352, 3857, 3201, 4970, 9990, 6707, 2799, 2899, 5013, 7525, 2858, 6305, 3769, 2826, 2945, 1472, 5112, 1327, 7025, 1359, 7013, 553, 844, 1362, 695, 5961, 3156, 6277, 7156, 6059, 8032, 3221, 6163, 7709, 7216, 3125, 6861, 261, 3696, 8058, 2012, 1311, 5834, 1365, 6733, 7691, 3845, 2953, 4467, 1903, 2038, 11, 3029, 4672, 10808,

Name: 6459, dtype: object
id                                                       89222
author                                                     NaN
source                                                TechWeb@
content      刘强东表示，昨天晚上，全体总部京东人几乎都是整夜未眠，令人感动的是还有5000名合作伙伴陪伴...
feature      {"type":"趣闻","site":"cnbeta","commentNum":"62"...
title                                 京东618全员参战 刘强东晒加班餐：小龙虾用盆装
url            http://hot.cnbeta.com/articles/funny/623753.htm
is_xinhua                                                    0
Name: 395, dtype: object
id                                                       77013
author                                                     杨丁淼
source                                                     新华社
content      　　新华社合肥４月２日电（记者杨丁淼）记者从中科院合肥物质科学研究院了解到，我国专家成功研制...
feature      {"type":"科技","site":"新华社","url":"http://home.x...
title                               （科技）专家成功研制可规模化制造的石墨烯基超级电容器
url          http://home.xinhua-news.com/gdsdetailxhsnew/17...
is_x

Name: 69, dtype: object
id                                                       89085
author                                                     NaN
source                                                    参考消息
content      日媒称，在巴基斯坦，中国主导“一带一路”倡议的基础项目正在切实推进。人们对中国拉动经济增长的...
feature      {"type":"国际","site":"头条","commentNum":"558","j...
title                               日媒走访“中巴经济走廊”建设现场：与中国比日本太迟钝
url          https://www.toutiao.com/group/6433398705881809...
is_xinhua                                                    0
Name: 532, dtype: object
id                                                       89424
author                                                     NaN
source                                              cnBeta.COM
content      论坛网名为Jozinek的用户表示：“该系统的安装包要比Android 6.0 Marshm...
feature      {"type":"科技","site":"cnbeta","commentNum":"7",...
title               [视频]Xperia XA率先升级Android 7.0：比6.0释放1GB存储空间
url             http://www.cnbeta.com/articles/tech/623695.htm
is_xin

Name: 406, dtype: object
id                                                       83311
author                                                     NaN
source                                                成都商报第06版
content      ??去年7月31日，成都地铁3号线正式开通运营，其中熊猫大道站的一面《熊猫大使》文化墙，引来...
feature      {"type":"要闻","site":"成都商报","commentNum":"0","j...
title                                     “我画的熊猫，咋出现在地铁站文化墙上？”
url          http://e.chengdu.cn/html/2017-06/23/content_59...
is_xinhua                                                    0
Name: 6306, dtype: object
id                                                       83444
author                                                     NaN
source                                               海南日报第008版
content      　　记者了解到，本次活动包括公开投票抽奖、征集修改意见、征集设计作品等3个部分。其中，修改意...
feature      {"type":"澄迈新发展","site":"海南日报","commentNum":"0"...
title                                             澄迈征集评选城市形象标志
url          http://hnrb.hinews.cn/html/2017-06/23/content_...
is_x

Name: 12605, dtype: object
id                                                       87124
author                                                     NaN
source                                                科技成果转化联盟
content      北京2017年6月19日电/美通社/ -- 2017年6月8-10日，第二十届中国北京国际科...
feature      {"type":"科技","site":"环球","commentNum":"0","joi...
title                                       联盟“工业强基成果展”首次亮相科博会
url          http://tech.huanqiu.com/news/2017-06/10867866....
is_xinhua                                                    0
Name: 2493, dtype: object
id                                                       89115
author                                                     高鑫戈
source                                                     人民网
content      　　2017年世界男排联赛第二档次昆山站比赛，主场作战的中国队面对亚洲的老对手日本队。尽管两...
feature      {"type":"体育","site":"环球","commentNum":"0","joi...
title                                 世界男排联赛中国追5赛点 3-2逆转日本主场夺冠
url          http://sports.huanqiu.com/others/zh/2017-06/10...
is

In [170]:
#使用LogisticRegression方法
from sklearn.linear_model import LogisticRegression
clf_logistic = LogisticRegression(random_state=0, solver='lbfgs',multi_class='multinomial').fit(x_train, y_train)


In [171]:
get_performance(clf_logistic,x_test,y_test)
y_predict_logistic=clf_logistic.predict(x_test)
print(y_predict_logistic)
print(np.array(y_test))
getresult(y_predict_logistic)


f1_score is  0.9299867899603699
accuracy_score is  0.93375
precision_score is  0.9887640449438202
recall_score is  0.8778054862842892
[0 1 0 ... 0 1 0]
[0 1 0 ... 0 1 0]
8
[4526, 6310, 5238, 7833, 3491, 2401, 4124, 1485]
id                                                       85083
author                                                     NaN
source                                               广州日报第A25版
content      “我到了‘假’店吗？”\r\n　　在消费行业竞争越来越激烈的当下，不管是实体店之间，还是电商...
feature      {"type":"悦生活","site":"广州日报","commentNum":"0","...
title                                              “我到了‘假’店吗？”
url          http://gzdaily.dayoo.com/html/2017-06/22/conte...
is_xinhua                                                    0
Name: 4534, dtype: object
id                                                       83253
author                                                     NaN
source                                                南方日报第01版
content      近年来，广东金融业在“支持创新发展、支持实体经济、支持对外开放”的总体要求下，不断改革创新，.

In [172]:
#svm
from sklearn import svm
clfsvm=svm.SVC(gamma='scale',kernel='linear')
clfsvm.fit(x_train, y_train)

SVC(C=1.0, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [173]:
get_performance(clfsvm,x_test,y_test)

f1_score is  0.9504185447520928
accuracy_score is  0.951875
precision_score is  0.9826897470039947
recall_score is  0.9201995012468828


In [176]:
y_predict_svm=clfsvm.predict(x_test)
getresult(y_predict_svm)

13
[4526, 6310, 5238, 1600, 6515, 7833, 3491, 6529, 2401, 7504, 1485, 5924, 7726]
id                                                       85083
author                                                     NaN
source                                               广州日报第A25版
content      “我到了‘假’店吗？”\r\n　　在消费行业竞争越来越激烈的当下，不管是实体店之间，还是电商...
feature      {"type":"悦生活","site":"广州日报","commentNum":"0","...
title                                              “我到了‘假’店吗？”
url          http://gzdaily.dayoo.com/html/2017-06/22/conte...
is_xinhua                                                    0
Name: 4534, dtype: object
id                                                       83253
author                                                     NaN
source                                                南方日报第01版
content      近年来，广东金融业在“支持创新发展、支持实体经济、支持对外开放”的总体要求下，不断改革创新，...
feature      {"type":"封面","site":"南方日报","commentNum":"0","j...
title                                            金融促进创新 网罗天下英才
url       

In [177]:
#Bayes-GaussianNB
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(x_train, y_train)

GaussianNB(priors=None, var_smoothing=1e-09)

In [178]:
get_performance(gnb,x_test,y_test)

f1_score is  0.8100208768267223
accuracy_score is  0.829375
precision_score is  0.9165354330708662
recall_score is  0.7256857855361596


In [179]:
y_predict_bayes_GaussianNB=gnb.predict(x_test)
getresult(y_predict_bayes_GaussianNB)

53
[708, 6131, 6905, 6876, 6032, 6310, 7524, 5539, 6427, 4650, 7216, 8058, 4598, 7956, 6640, 6419, 3518, 10960, 7756, 3926, 610, 6398, 6021, 3491, 8052, 7340, 6017, 10047, 7350, 4124, 5955, 1916, 1936, 1993, 443, 3836, 10713, 7838, 4258, 7504, 6083, 1963, 1941, 216, 4030, 1353, 10594, 7726, 5804, 5247, 4987, 4351, 4493]
id                                                       88907
author                                                      李芳
source                                                     环球网
content      　　6月18日，由中国汽车评价研究院主办、龙蟠润滑油冠名赞助的首届“龙蟠杯”世界十佳变速器评...
feature      {"type":"汽车","site":"环球","commentNum":"0","joi...
title                                   首届“龙蟠杯”世界十佳变速器评选活动正式启动
url          http://auto.huanqiu.com/news/2017-06/10866557....
is_xinhua                                                    0
Name: 710, dtype: object
id                                                       83437
author                                                     NaN
source                 

id                                                       82192
author                                                     NaN
source                                               海南日报第008版
content                                　　特约记者?吴文生?通讯员?王荣?摄\r\n
feature      {"type":"海南新闻经济","site":"海南日报","commentNum":"0...
title                                                儋州海花岛初现雏形
url          http://hnrb.hinews.cn/html/2017-06/22/content_...
is_xinhua                                                    0
Name: 7425, dtype: object
id                                                       85485
author                                                     NaN
source                                             广州日报第SZA16版
content      “星期三查餐厅” 开进西乡中学食堂\r\n　　广州日报讯 （记者阮元元 通讯员崔艳艳）昨日，...
feature      {"type":"区街事","site":"广州日报","commentNum":"0","...
title                                         “星期三查餐厅”开进西乡中学食堂
url          http://gzdaily.dayoo.com/html/2017-06/22/conte...
is_xinhua                    

In [180]:
#Bayes-MultinomialNB
from sklearn.naive_bayes import MultinomialNB
gnb_multi = MultinomialNB()
gnb_multi.fit(x_train, y_train)
get_performance(gnb_multi,x_test,y_test)

f1_score is  0.8365180467091295
accuracy_score is  0.855625
precision_score is  0.967266775777414
recall_score is  0.7369077306733167


In [181]:
#Bayes-BernoulliNB
from sklearn.naive_bayes import BernoulliNB
gnb_bernoul = BernoulliNB()
gnb_bernoul.fit(x_train, y_train)
get_performance(gnb_bernoul,x_test,y_test)

f1_score is  0.7952755905511811
accuracy_score is  0.7725
precision_score is  0.7243852459016393
recall_score is  0.8815461346633416


In [182]:
#Bayes-BernoulliNB
from sklearn.naive_bayes import ComplementNB
gnb_complement = ComplementNB()
gnb_complement.fit(x_train, y_train)
get_performance(gnb_complement,x_test,y_test)

f1_score is  0.8365180467091295
accuracy_score is  0.855625
precision_score is  0.967266775777414
recall_score is  0.7369077306733167


In [183]:
#random forest
from sklearn.ensemble import RandomForestClassifier
rfc=RandomForestClassifier(random_state=0,n_estimators= 70)
rfc.fit(x_train,y_train)

RandomForestClassifier(bootstrap=True, class_weight=None, criterion='gini',
                       max_depth=None, max_features='auto', max_leaf_nodes=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=70,
                       n_jobs=None, oob_score=False, random_state=0, verbose=0,
                       warm_start=False)

In [184]:
score_l=rfc.score(x_train,y_train)
score_r=rfc.score(x_test,y_test)
print(score_l)
print(score_r)
get_performance(rfc,x_test,y_test)

0.99984375
0.899375
f1_score is  0.8917283120376597
accuracy_score is  0.899375
precision_score is  0.9678832116788321
recall_score is  0.8266832917705735


In [185]:
y_predict_randomforest=rfc.predict(x_test)
getresult(y_predict_randomforest)

22
[10817, 4526, 6310, 10599, 3237, 5317, 3491, 8052, 7340, 6474, 6650, 4018, 4320, 6308, 6472, 7824, 5214, 10971, 5313, 4493, 5127, 5630]
id                                                       76238
author                                                      马平
source                                                     新华社
content      新华社照片，东京，2017年4月3日\n（国际）（4）樱花烂漫时\n4月3日，在日本东京，人...
feature      {"type":"政治法律","site":"新华社","url":"http://home...
title                                             （国际）（4）樱花烂漫时
url          http://home.xinhua-news.com/gdsdetailxhsnew/17...
is_xinhua                                                    1
Name: 13374, dtype: object
id                                                       85083
author                                                     NaN
source                                               广州日报第A25版
content      “我到了‘假’店吗？”\r\n　　在消费行业竞争越来越激烈的当下，不管是实体店之间，还是电商...
feature      {"type":"悦生活","site":"广州日报","commentNum":"0","...
title          

### Step10： 总结该过程，什么是数据思维？什么是机器学习思维？

### (Optional)使用第4课讲解的 edit distance，在涉嫌抄袭的文章中，找到其重复的文字与被修改过的文字。 

### Step11: 利用第8课讲述的新模型，进行操作，感受其中不同的参数、模型对性能的影响。